### ISSUE TITLE
[Feature/Idea]: Use @v1 for versioning

### ISSUE THREAD

**Issue by CodeDoctorDE** [vedantmgoyal2009/winget-releaser#11]
### What would you like to see changed/added?

If you have a breaking change in your configuration, it would be useful to use @v1, @v2 that you can safely migrate

**Comment by russellbanks** [comment]
I would vouch for this too. I think @vedantmgoyal2009's intention for using the latest tag was that it is highly unlikely that there will ever be a breaking change as the core logic for WinGet Releaser will likely never change, so users will always be able to have the latest changes and fixes.

However, users would be remaining up-to-date by using the @v1 tag (like the latest tag is doing) anyway. On the off-chance that there is ever a breaking change, then we can create @v2 and worst-case scenario, we just make pull requests to repositories that use an outdated version.

This could also mean that we get more clarity on changes, rather than reading commit history. For example, there is a minor bug fix/update, so we create `1.1.0`. Users won't need to change anything to have that update, but anyone that does check will have a clear view that `1.1.0`, for example, added support for 1.4.0 manifests, etc.

**Comment by russellbanks** [comment]
[GitHub themselves even advise that developers release a major version update](https://github.blog/changelog/2022-05-20-actions-can-now-run-in-a-node-js-16-runtime/), just for updating NodeJS to a new LTS version (e.g. 16 -> 18). Now that WinGet Releaser uses Javascript, it is more important to note this because NodeJS 18 becomes an LTS release in just a couple months time.

**Comment by vedantmgoyal9** [comment]
> we just make pull requests to repositories that use an outdated version

I'm currently looking that how can I automate this part. Once it is done, I will create PRs to replace all `@latest` with `@v1`.

**Comment by sitiom** [comment]
> we just make pull requests to repositories that use an outdated version

Or suggest adding Dependabot to those repositories

**Comment by vedantmgoyal9** [comment]
Sure, dependabot can be added, but some users or organisations might not want to add it to their repo. That's why I've added a logic to auto-update the action and automatically create a PR to update itself.
