### ISSUE TITLE
[Feature/Idea]: Add warning for outdated Winget Releaser version

### ISSUE THREAD

**Issue by sitiom** [vedantmgoyal2009/winget-releaser#115]
### What would you like to see changed/added?

When the action doesn't have permission to bump the Winget Releaser version, add a warning in the output instead and point to the new version.

**Comment by vedantmgoyal9** [comment]
This is what I'm thinking to do along with removing the auto-update logic from the action, and instead recommending users add dependabot to their repositories. 

It is because I think some maintainers who are extremely careful about their account's security might perceive it in a negative sense as if the action is doing other things on their behalf other than its designated purpose (since it will open a PR on the source-code repo with the user's PAT). Factors like the action not being widely recognized, coming from an individual developer, and the low number of stars, add up and people might think that the action can also perform some malicious action on their behalf, therefore, they should refrain from adding it to their repository.

Also, this feature of my action can conflict (resulting in multiple action version update PRs) when any other automatic update bot like renovate, dependabot, etc. is already present in the repo. In fact, @sitiom has been adding dependabot configuration to the repositories, and it seems like it is acceptable to the maintainers. 

@daiyam @russellbanks What are your views on this? I think the idea of a warning is good instead of auto-update logic.

**Comment by daiyam** [comment]
Oh! Yes, remove the auto-update and just output an error if the action isn't running the correct version you want.

By the way, for me, the update failed and got weird error (https://github.com/VSCodium/vscodium/actions/runs/4319298031/jobs/7538998789) which pushed me to update to v2.

**Comment by sitiom** [comment]
Related to #104
