### ISSUE TITLE
[Feature/Idea]: Ability to disable filling in the `PublisherUrl`

### ISSUE THREAD

**Issue by sitiom** [vedantmgoyal2009/winget-releaser#162]
### What would you like to see changed/added?

- https://github.com/coreybutler/nvm-windows/pull/885#issuecomment-1554806358
- https://github.com/microsoft/winget-pkgs/pull/105831#issuecomment-1534067169

There are also other packages like this that have websites from the profile unrelated to the `PublisherUrl`. Maybe have a parameter to set a custom `PublisherUrl`.

Ping @russellbanks

**Comment by vedantmgoyal9** [comment]
@sitiom I've created a PR on komac's repo to get repository homepage first and if it's null, then go for website from profile. I hope that won't affect other packages. Please test it once v1.8.1 of komac is released.

**Comment by sitiom** [comment]
> @sitiom I've created a PR on komac's repo to get repository homepage first and if it's null, then go for website from profile.

Nice feature, but shouldn't that be for the `PackageUrl` instead? Also, I made this issue to disable the `PublisherUrl` altogether because the links were getting a 404 error in the Winget CI for some reason (although they do work).

**Comment by vedantmgoyal9** [comment]
`PackageUrl` is GitHub repository.

**Comment by vedantmgoyal9** [comment]
@sitiom I've updated Komac to set the publisher URL as the website from the profile if the user is an organization, else it will default to the GitHub profile URL. I think this will be the best approach to handle this since users can have URLs on their profile unrelated to the project, but organizations will usually have a proper website. I'm a bit hesitant to add another input to disable filling Publisher URL since it will require additional implementation in Komac.
