### ISSUE TITLE
[Feature/Idea]: Add option for specifying Komac version

### ISSUE THREAD

**Issue by russellbanks** [vedantmgoyal2009/winget-releaser#187]
### What would you like to see changed/added?

It would be good to have an option for what version of Komac to use. This should default to latest.

```yaml
komac-version: latest
```
```yaml
komac-version: nightly
```
```yaml
komac-version: 1.9.0
```

Specifically, this should really only really be used if there is a regression that affects a publisher's package and they temporarily need to use an older version or if there is a fix that is available in nightly but not in stable yet.

**Comment by vedantmgoyal9** [comment]
When the `latest` version of Komac fails after a GitHub release is published, the maintainer faces challenges in modifying the workflow for re-running the job, because the rerun would take place in the old context, and to use the specified Komac version, the maintainer has to delete both the tag and the release or resort to force-pushing the tag, deleting the release, and creating them again. However, these steps can result in increased CI costs for maintainers who are on a paid plan, as they would have to rebuild the binaries of the application. Additionally, in organizations or projects where multiple teams are involved, performing these steps more than one time becomes impractical and cumbersome. 

We've tried encouraging users to add winget-releaser to their CI process to streamline the intricate workflow of publishing their application's releases to WinGet. However, some users remain hesitant to adopt this approach.

Avoiding action inputs for controlling Komac versions is preferred to enable easy switching when re-running workflow jobs, offering more flexibility. However, when relying on action inputs, users can forget to revert to the `latest`, hindering upgrades and going against the action's purpose to handle all changes & upgrades effectively.
