### ISSUE TITLE
Transparency: Tag releases, provide version history, do not delete commits for published versions

### ISSUE THREAD

**Issue by fredemmott** [vedantmgoyal2009/winget-releaser#291]
### What would you like to see changed/added?

- The v2 release links to the diff between v1 and v2, however the v1 tag has not been modified in years: https://github.com/vedantmgoyal2009/winget-releaser/releases/tag/v1
- https://github.com/vedantmgoyal2009/winget-releaser/commit/2d5bb869756ba21df74099058ee420ddca7c3d77 was a published release (https://github.com/OpenKneeboard/OpenKneeboard/pull/481) but is no longer available in any branches
- as such, it's extremely difficult to keep track of what's changed
- as [we previously discussed](https://github.com/OpenKneeboard/OpenKneeboard/pull/371#discussion_r1235326617
), rewriting history also breaks dependabot, e.g. I've not had any PRs to OpenKneeboard since you removed the commit linked above

I'll be removing the workflow for now; I can't give secrets/credentials to a workflow without more transparency and the ability to easily see what's changed.

**Comment by vedantmgoyal9** [comment]
Hi,

I've decided not to maintain any tag releases. Instead, users can use the `main` branch directly, or commit hashes. Also, commit history will be version history.

I have decided so because the action is mostly a wrapper around Komac, the tool that handles manifests updation/creation, and requires updates/modifications only when there are breaking changes in Komac.

I will remove the tag releases once all repositories are migrated to use the main branch OR commit hashes + dependabot setup.
