### ISSUE TITLE
[Bug]: Action no longer runs

### ISSUE THREAD

**Issue by doug24** [vedantmgoyal2009/winget-releaser#294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have been using this action on the dnGrep.dnGrep project for a few years now and on my last two monthly releases (including today) the action did not run - no errors, just didn't run at all.  My configuration looks just like the minimal configuration example.  I have a up to date classic token. The fork of the winget-pkgs is up to date. 

I don't know what has gone wrong.

**Comment by vedantmgoyal9** [comment]
I have been waiting for @russellbanks to release a new version so that I can update the action to use the Komac v2. There have been a lot of issues lately as it was completely re-written from Kotlin to Rust, so I thought to wait till it gets stable. I will update the action with the next Komac 2 release.

**Comment by doug24** [comment]
Thank-you for the update

**Comment by vedantmgoyal9** [comment]
@doug24 I've updated the action. You just need to replace `vedantmgoyal2009/winget-releaser@v2` with `vedantmgoyal9/winget-releaser@main`.
