### ISSUE TITLE
[Bug]: doesn't pick the previous manifest from my fork of winget-pkgs

### ISSUE THREAD

**Issue by assarbad** [vedantmgoyal2009/winget-releaser#309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi,

I was trying to create [a mock manifest](https://github.com/assarbad/winget-pkgs/commit/ca5a0a8fd21) for `WinDirStat.WinDirStat` on `master` of my fork of `winget-pkgs`.

The reason I seem to need a mock manifest is that the original manifest doesn't support all the architectures and there are a handful of outdated items ([xref 1.1.2](https://github.com/microsoft/winget-pkgs/tree/master/manifests/w/WinDirStat/WinDirStat/1.1.2)).

Given the documentation I assumed that `winget-releaser` (or is that part from `komac`?) would be using the manifest from my fork regardless. It doesn't seem to do so.

Is this a limitation of `winget-releaser` (or `komac`) or is this ticket wrong and there's a way to achieve what I want somehow?

**Comment by vedantmgoyal9** [comment]
The previous manifest is always fetched from microsoft/winget-pkgs.

The fork-user input is used to specify fork of winget-pkgs from which PR to microsoft/winget-pkgs will be made.

For example, action is running under `example-org/example` repo. However, sometimes the maintainer doesn't like to fork microsoft/winget-pkgs under the organization to keep it clean and would prefer to fork under their personal account. So, they can specify `fork-user` input to tell the action (actually, komac since it handles the manifest creation) to use fork of winget-pkgs present under that specified GitHub account.

**Comment by assarbad** [comment]
Oh, I see. So in essence if _too much_ has changed in the manifest it needs to be edited manually _once_ before `winget-releaser` can take over? Thanks for the clarification. In that case it's hardly a defect of `winget-releaser`.

Oh and btw: _thanks_ for this tool and generally for your efforts within the WinGet community. I ran across your name numerous times already in matters WinGet.
